### PR TITLE
Two counters, updated cover

### PR DESCRIPTION
**Pull request by direc85**
There are now two counters side by side, and both counters can be increased from cover screen. Also many small improvements and cleaning.

### CODE REVIEW

**Comment by direc85** [comment]
Are you going to accept this? Are you still developing this software?

**Comment by direc85** [comment]
Do you mind if I publish my fork in Jolla Store?

**Comment by AlphaX2** [comment]
Hi,

I have totaly no time to code and no active Jolla device to care about it
anymore, but it's open source - so yes please, modify and release as much
as you want. ;-)

Thank you very much for your time and effort! :)


Am Di., 27. Nov. 2018, 23:06 hat Matti Viljanen <notifications@github.com>
geschrieben:

**Comment by direc85** [comment]
I released my CountMe 2 app years ago, so I'll close this PR finally.

All the best to you!

**Pull request closed without merging**
